---
- name: Create directory for immich
  ansible.builtin.file:
    name: /home/{{ ansible_user }}/immich
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: immich/immich_compose.yaml.j2
    dest: /home/{{ ansible_user }}/immich/compose.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"

- name: Deploy immich env
  ansible.builtin.template:
    src: immich/immich_env.j2
    dest: /home/{{ ansible_user }}/immich/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"

- name: Run immich
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/immich
